# Generated by Django 5.2.7 on 2025-10-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_categoria', models.IntegerField()),
                ('precio_u', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('id_proveedor', models.IntegerField()),
            ],
        ),
    ]
